[package]
name = "candle-rec"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features=["derive"] }
csv = "1.3.1"
rand = "0.9.0"
candle-core = "0.8.4"
candle-nn = "0.8.4"
candle-optimisers = "0.8.0"
anyhow = "1.0.97"